### ISSUE TITLE
websocket use

### ISSUE THREAD

**Issue by 317459062** [firepol/ccxt-websockets#1]
how can i use websocket in huobipro and zb for 'ob' and trade?
can u take a detail steps?
thx

**Comment by firepol** [comment]
Hello, try this project: https://github.com/firepol/ccxt-websockets-db-updater

In the readme you find examples on how to use it. Try e.g. `ob_tester.py`

If you have problems, please do not post issues in this repository, but in the lfern thread of in the `ccxt-websockets-db-updater` issues. Thanks.
